### ISSUE TITLE
'unexpected key "cnn.7.num_batches_tracked" in state_dict'

### ISSUE THREAD

**Issue by NK-Hubert** [chenjun2hao/Attention_ocr.pytorch#7]
运行demo.py的时候，出错？
loading pretrained models ......
Traceback (most recent call last):
  File "demo.py", line 34, in <module>
    encoder.load_state_dict(torch.load(encoder_path))
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "cnn.7.num_batches_tracked" in state_dict'

**Comment by NK-Hubert** [comment]
换了0.4的pytorch解决了，版本问题
